# Generated by Django 4.1.5 on 2023-01-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_owner_alter_task_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
