# Generated by Django 4.1.5 on 2023-01-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
